apiVersion : apps/v1
kind: Deployment
metadata:
  name: "cryptshareaks-57e3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "cryptshareaks-57e3"
  template:
    metadata:
      labels:
        app: "cryptshareaks-57e3"
    spec:
      containers:
        - name: "cryptshareaks-57e3"
          image: "crytpfilesharerepo.azurecr.io/cryptshareaks"
          ports:
          - containerPort: 3000