on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: crytpfilesharerepo.azurecr.io
        username: ${{ secrets.acr_crytpfilesharerepo_username }}
        password: ${{ secrets.acr_crytpfilesharerepo_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t crytpfilesharerepo.azurecr.io/cryptshareaks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push crytpfilesharerepo.azurecr.io/cryptshareaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_cryptshareaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep cryptshare | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace cryptshare`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: cryptshare
        container-registry-url: crytpfilesharerepo.azurecr.io
        container-registry-username: ${{ secrets.acr_crytpfilesharerepo_username }}
        container-registry-password: ${{ secrets.acr_crytpfilesharerepo_password }}
        secret-name: cryptshareakdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: cryptshare
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          crytpfilesharerepo.azurecr.io/cryptshareaks:${{ github.sha }}
        imagepullsecrets: |
          cryptshareakdockerauth
